# #  <<<<<<<<<program for chatting between two person >>>>>>

# import pyttsx3
# engine = pyttsx3.init()
# engine.setProperty("volume",2.0)
# engine.setProperty("rate",150)
# a = ("<<<<<<<< Welcome to chatting >>>>>>>>>>")
# print(a)
# engine.say(a)
# engine.runAndWait()
# print()
# print("MADE BY: BIJENDER\nDATE: 8th APRIL\nCONTACT: 8800461382")
# print()
# s=input("Press 1 to start chatting: ")
# print()
# print("<<< Enter the Name of person with whom you wants to talk >>>")
# engine.say("enter the name of person with whom you wants to talk")
# engine.runAndWait()
# print()
# b=input("First Person Name:  ")
# c=input("Second Person Name: ")
# print()
# print( b,"and",c, "are connected to call.")
# print()
# while True:
# 	p1=input(b+":  ")
# 	engine.say(p1)
# 	engine.runAndWait()
# 	print()
# 	p2=input(c+":  ")
# 	engine.say(p2)
# 	engine.runAndWait()
# 	print()
# 	if p1==p2:
# 		p = ("Great both of you talk well.")
# 		print(p)
# 		engine.say(p)
# 		engine.runAndWait()
# 		break